//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in BySeverity) DeepCopyInto(out *BySeverity) {
	{
		in := &in
		*out = make(BySeverity, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BySeverity.
func (in BySeverity) DeepCopy() BySeverity {
	if in == nil {
		return nil
	}
	out := new(BySeverity)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContainerImageScan) DeepCopyInto(out *ContainerImageScan) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContainerImageScan.
func (in *ContainerImageScan) DeepCopy() *ContainerImageScan {
	if in == nil {
		return nil
	}
	out := new(ContainerImageScan)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ContainerImageScan) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContainerImageScanList) DeepCopyInto(out *ContainerImageScanList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ContainerImageScan, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContainerImageScanList.
func (in *ContainerImageScanList) DeepCopy() *ContainerImageScanList {
	if in == nil {
		return nil
	}
	out := new(ContainerImageScanList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ContainerImageScanList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContainerImageScanSpec) DeepCopyInto(out *ContainerImageScanSpec) {
	*out = *in
	in.ImageScanSpec.DeepCopyInto(&out.ImageScanSpec)
	out.Workload = in.Workload
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContainerImageScanSpec.
func (in *ContainerImageScanSpec) DeepCopy() *ContainerImageScanSpec {
	if in == nil {
		return nil
	}
	out := new(ContainerImageScanSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContainerImageScanStatus) DeepCopyInto(out *ContainerImageScanStatus) {
	*out = *in
	if in.LastScanTime != nil {
		in, out := &in.LastScanTime, &out.LastScanTime
		*out = (*in).DeepCopy()
	}
	if in.LastSuccessfulScanTime != nil {
		in, out := &in.LastSuccessfulScanTime, &out.LastSuccessfulScanTime
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Vulnerabilities != nil {
		in, out := &in.Vulnerabilities, &out.Vulnerabilities
		*out = make([]Vulnerability, len(*in))
		copy(*out, *in)
	}
	if in.VulnerabilitySummary != nil {
		in, out := &in.VulnerabilitySummary, &out.VulnerabilitySummary
		*out = new(VulnerabilitySummary)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContainerImageScanStatus.
func (in *ContainerImageScanStatus) DeepCopy() *ContainerImageScanStatus {
	if in == nil {
		return nil
	}
	out := new(ContainerImageScanStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Image) DeepCopyInto(out *Image) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Image.
func (in *Image) DeepCopy() *Image {
	if in == nil {
		return nil
	}
	out := new(Image)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImageScanSpec) DeepCopyInto(out *ImageScanSpec) {
	*out = *in
	out.Image = in.Image
	in.ScanConfig.DeepCopyInto(&out.ScanConfig)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImageScanSpec.
func (in *ImageScanSpec) DeepCopy() *ImageScanSpec {
	if in == nil {
		return nil
	}
	out := new(ImageScanSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScanConfig) DeepCopyInto(out *ScanConfig) {
	*out = *in
	if in.MinSeverity != nil {
		in, out := &in.MinSeverity, &out.MinSeverity
		*out = new(string)
		**out = **in
	}
	if in.IgnoreUnfixed != nil {
		in, out := &in.IgnoreUnfixed, &out.IgnoreUnfixed
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScanConfig.
func (in *ScanConfig) DeepCopy() *ScanConfig {
	if in == nil {
		return nil
	}
	out := new(ScanConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Vulnerability) DeepCopyInto(out *Vulnerability) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Vulnerability.
func (in *Vulnerability) DeepCopy() *Vulnerability {
	if in == nil {
		return nil
	}
	out := new(Vulnerability)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VulnerabilitySummary) DeepCopyInto(out *VulnerabilitySummary) {
	*out = *in
	if in.SeverityCount != nil {
		in, out := &in.SeverityCount, &out.SeverityCount
		*out = make(map[string]int32, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VulnerabilitySummary.
func (in *VulnerabilitySummary) DeepCopy() *VulnerabilitySummary {
	if in == nil {
		return nil
	}
	out := new(VulnerabilitySummary)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Workload) DeepCopyInto(out *Workload) {
	*out = *in
	out.GroupKind = in.GroupKind
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Workload.
func (in *Workload) DeepCopy() *Workload {
	if in == nil {
		return nil
	}
	out := new(Workload)
	in.DeepCopyInto(out)
	return out
}
