---
version: "2"
linters:
  enable:
    - errname
    - errorlint
    - goconst
    - gocritic
    - godot
    - gosec
    - predeclared
    - unparam
    - whitespace
    - wsl_v5
  settings:
    gocritic:
      enabled-checks:
        - importShadow
    wsl_v5:
      allow-first-in-block: true
      allow-whole-block: false
      branch-max-lines: 2
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/statnett/image-scanner-operator
