---
version: "2"
linters:
  enable:
    - errname
    - errorlint
    - goconst
    - gocritic
    - godot
    - gosec
    - predeclared
    - unparam
    - whitespace
    - wsl_v5
  settings:
    gocritic:
      enabled-checks:
        - importShadow
    wsl_v5:
      allow-first-in-block: true
      allow-whole-block: false
      branch-max-lines: 2
formatters:
  enable:
    - gci
    - gofmt
  settings:
    gci:
      sections:
        - standard # Standard section: captures all standard packages.
        - default # Default section: contains all imports that could not be matched to another section type.
        - prefix(github.com/statnett/image-scanner-operator) # Custom section: groups all imports with the specified prefix.
