extends: default
ignore: |
  /config/crd/bases/
  /config/rbac/role.yaml
  /config/openreports/crd/
rules:
  comments:
    require-starting-space: false
  document-start: disable
  line-length:
    max: 140
    allow-non-breakable-inline-mappings: true
