// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	godigest "github.com/opencontainers/go-digest"
	stasv1alpha1 "github.com/statnett/image-scanner-operator/api/stas/v1alpha1"
)

// ContainerImageScanSpecApplyConfiguration represents a declarative configuration of the ContainerImageScanSpec type for use
// with apply.
//
// ContainerImageScanSpec contains a resolved container image in use by owning workload.
type ContainerImageScanSpecApplyConfiguration struct {
	ImageScanSpecApplyConfiguration `json:",inline"`
	Tag                             *string                     `json:"tag,omitempty"`
	Workload                        *WorkloadApplyConfiguration `json:"workload,omitempty"`
}

// ContainerImageScanSpecApplyConfiguration constructs a declarative configuration of the ContainerImageScanSpec type for use with
// apply.
func ContainerImageScanSpec() *ContainerImageScanSpecApplyConfiguration {
	return &ContainerImageScanSpecApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *ContainerImageScanSpecApplyConfiguration) WithName(value string) *ContainerImageScanSpecApplyConfiguration {
	b.ImageApplyConfiguration.Name = &value
	return b
}

// WithDigest sets the Digest field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Digest field is set to the value of the last call.
func (b *ContainerImageScanSpecApplyConfiguration) WithDigest(value godigest.Digest) *ContainerImageScanSpecApplyConfiguration {
	b.ImageApplyConfiguration.Digest = &value
	return b
}

// WithMinSeverity sets the MinSeverity field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MinSeverity field is set to the value of the last call.
func (b *ContainerImageScanSpecApplyConfiguration) WithMinSeverity(value stasv1alpha1.Severity) *ContainerImageScanSpecApplyConfiguration {
	b.ScanConfigApplyConfiguration.MinSeverity = &value
	return b
}

// WithIgnoreUnfixed sets the IgnoreUnfixed field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the IgnoreUnfixed field is set to the value of the last call.
func (b *ContainerImageScanSpecApplyConfiguration) WithIgnoreUnfixed(value bool) *ContainerImageScanSpecApplyConfiguration {
	b.ScanConfigApplyConfiguration.IgnoreUnfixed = &value
	return b
}

// WithTag sets the Tag field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Tag field is set to the value of the last call.
func (b *ContainerImageScanSpecApplyConfiguration) WithTag(value string) *ContainerImageScanSpecApplyConfiguration {
	b.Tag = &value
	return b
}

// WithWorkload sets the Workload field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Workload field is set to the value of the last call.
func (b *ContainerImageScanSpecApplyConfiguration) WithWorkload(value *WorkloadApplyConfiguration) *ContainerImageScanSpecApplyConfiguration {
	b.Workload = value
	return b
}
