// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	godigest "github.com/opencontainers/go-digest"
)

// ImageApplyConfiguration represents a declarative configuration of the Image type for use
// with apply.
type ImageApplyConfiguration struct {
	Name   *string          `json:"name,omitempty"`
	Digest *godigest.Digest `json:"digest,omitempty"`
}

// ImageApplyConfiguration constructs a declarative configuration of the Image type for use with
// apply.
func Image() *ImageApplyConfiguration {
	return &ImageApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *ImageApplyConfiguration) WithName(value string) *ImageApplyConfiguration {
	b.Name = &value
	return b
}

// WithDigest sets the Digest field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Digest field is set to the value of the last call.
func (b *ImageApplyConfiguration) WithDigest(value godigest.Digest) *ImageApplyConfiguration {
	b.Digest = &value
	return b
}
