// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	godigest "github.com/opencontainers/go-digest"
	stasv1alpha1 "github.com/statnett/image-scanner-operator/api/stas/v1alpha1"
)

// ImageScanSpecApplyConfiguration represents a declarative configuration of the ImageScanSpec type for use
// with apply.
type ImageScanSpecApplyConfiguration struct {
	ImageApplyConfiguration      `json:",inline"`
	ScanConfigApplyConfiguration `json:",inline"`
}

// ImageScanSpecApplyConfiguration constructs a declarative configuration of the ImageScanSpec type for use with
// apply.
func ImageScanSpec() *ImageScanSpecApplyConfiguration {
	return &ImageScanSpecApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *ImageScanSpecApplyConfiguration) WithName(value string) *ImageScanSpecApplyConfiguration {
	b.ImageApplyConfiguration.Name = &value
	return b
}

// WithDigest sets the Digest field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Digest field is set to the value of the last call.
func (b *ImageScanSpecApplyConfiguration) WithDigest(value godigest.Digest) *ImageScanSpecApplyConfiguration {
	b.ImageApplyConfiguration.Digest = &value
	return b
}

// WithMinSeverity sets the MinSeverity field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MinSeverity field is set to the value of the last call.
func (b *ImageScanSpecApplyConfiguration) WithMinSeverity(value stasv1alpha1.Severity) *ImageScanSpecApplyConfiguration {
	b.ScanConfigApplyConfiguration.MinSeverity = &value
	return b
}

// WithIgnoreUnfixed sets the IgnoreUnfixed field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the IgnoreUnfixed field is set to the value of the last call.
func (b *ImageScanSpecApplyConfiguration) WithIgnoreUnfixed(value bool) *ImageScanSpecApplyConfiguration {
	b.ScanConfigApplyConfiguration.IgnoreUnfixed = &value
	return b
}
