---
# Prometheus Monitor Service (Metrics)
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  labels:
    control-plane: controller-manager
    app.kubernetes.io/name: servicemonitor
    app.kubernetes.io/instance: controller-manager-metrics-monitor
    app.kubernetes.io/component: metrics
    app.kubernetes.io/created-by: image-scanner-operator
    app.kubernetes.io/part-of: image-scanner-operator
    app.kubernetes.io/managed-by: kustomize
  name: controller-manager-metrics-monitor
  namespace: system
spec:
  podMetricsEndpoints:
    - honorLabels: true
      metricRelabelings:
        - sourceLabels:
            - namespace
          targetLabel: kubernetes_namespace
        - sourceLabels:
            - name
          targetLabel: kubernetes_name
        - action: labeldrop
          regex: endpoint|pod|container
      path: /metrics
      port: metrics
      scheme: http
