---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: image-scanner
resources:
  - network_policy.yaml
  - service.yaml
  - stateful_set.yaml
commonLabels:
  app.kubernetes.io/name: trivy
  app.kubernetes.io/component: server
configMapGenerator:
  - name: trivy
    literals:
      - LISTEN=0.0.0.0:4954
      - CACHE_DIR=/home/scanner/.cache/trivy
      - DB_REPOSITORY=ghcr.io/aquasecurity/trivy-db
