@startuml Image Scanner architecture
  () Pod as pod
  () ContainerImageScan as cis
  () Job as job

  [Workload controller] ..> pod : watch
  [Workload controller] --> cis : create/update
  [Workload controller] ..> cis : watch

  [CIS controller] ..> cis : watch
  [CIS controller] --> job : create

  [Scan Job controller] ..> job : watch
  [Scan Job controller] --> cis : update status
@enduml
