@startuml
autonumber 1.1

actor       User       as user
participant "Workload controller" as wc
entity      Pod      as pod
participant "CIS controller" as cc
entity      CIS      as cis
participant "Scan Job controller" as jc
entity      Job      as job
actor "K8s Garbage Collector" as gc

user -> pod : create
activate pod 

wc <<- pod :created
activate wc
wc -> cis : create
deactivate wc
activate cis

cc <<- cis : created
activate cc
cc -> job : create
note right of job
Job scans the pod
container image.
end note
deactivate cc
activate job

|||

jc <<- job: finished
activate jc
jc -> cis : update status
deactivate jc

|||

destroy job

|||

autonumber 2.1
user -> pod : delete
gc <<- pod: deleted
destroy pod
gc -> cis : delete
destroy cis
@enduml
