@startuml
autonumber

actor       User       as user
participant "Workload controller" as wc
entity      Pod      as pod
participant "CIS controller" as cc
entity      CIS      as cis
participant "Scan Job controller" as jc
entity      Job      as job

user -> pod : create
activate pod 

wc <<- pod :created
activate wc
wc -> cis : create
deactivate wc
activate cis

cc <<- cis : created
activate cc
cc -> job : create
note right of job
Scans the pod
container image.
end note
deactivate cc
activate job

|||

jc <<- job: finished
activate jc
jc -> cis : update status
deactivate jc
destroy job

@enduml
