---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../default
  - ../wg-policy
configMapGenerator:
  - name: image-scanner-config
    behavior: merge
    literals:
      # Only include chainsaw namespace pattern to reduce resource waste running e2e tests
      - SCAN_NAMESPACE_INCLUDE_REGEXP=^chainsaw-.*
  - name: trivy-server-config
    behavior: merge
    literals:
      - DB_REPOSITORY=public.ecr.aws/aquasecurity/trivy-db
  - name: trivy-job-config
    namespace: image-scanner
    behavior: merge
    literals:
      - JAVA_DB_REPOSITORY=public.ecr.aws/aquasecurity/trivy-java-db
patches:
  - patch: |-
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --feature-gates=PolicyReport=true
    target:
      kind: Deployment
      name: image-scanner-controller-manager
  # FIXME: Somehow sessionAffinity does not work when running e2e tests in some environments
  # Disable trivy server sessionAffinity; not really needed when running a single replica
  - patch: |-
      apiVersion: v1
      kind: Service
      metadata:
        name: trivy
      spec:
        sessionAffinity: None
  # Replace PVC with emptyDir for e2e-tests
  - patch: |-
      apiVersion: apps/v1
      kind: StatefulSet
      metadata:
        name: trivy
      spec:
        volumeClaimTemplates: []
        template:
          spec:
            volumes:
              - name: data
                emptyDir: {}
