---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../default
configMapGenerator:
  - name: image-scanner-config
    behavior: merge
    literals:
      # Only include kuttl namespace pattern to reduce resource waste running e2e tests
      - SCAN_NAMESPACE_INCLUDE_REGEXP=^kuttl-.*
  - name: trivy-job-config
    namespace: image-scanner
    behavior: merge
    literals:
      # See if "slow" config can improve stability
      - SLOW=true
