---
name: Clear cache
on:
  pull_request:
permissions:
  actions: write
jobs:
  clear-cache:
    runs-on: ubuntu-latest
    steps:
      - name: Clear cache
        run: |
          gh extension install actions/gh-actions-cache
          gh actions-cache delete --confirm
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}